import { z } from "zod";
import { MAX_MESSAGE_LENGTH } from "@/lib/chatSafety";

const publicIdParam = z.object({
  publicId: z.string().min(4).max(64),
});

export const listConversationsSchema = z.object({
  query: z.object({
    type: z.enum(["BOOKING", "SUPPORT"]).optional(),
    archived: z
      .enum(["0", "1", "true", "false"])
      .optional()
      .transform((v) => v === "1" || v === "true"),
    cursor: z.coerce.number().int().positive().optional(),
    take: z.coerce.number().int().min(1).max(50).optional(),
  }),
});

export const conversationParamSchema = z.object({ params: publicIdParam });

export const listMessagesSchema = z.object({
  params: publicIdParam,
  query: z.object({
    // Cursor, not page: a thread that gains a message between two requests
    // would otherwise repeat one or skip one.
    before: z.coerce.number().int().positive().optional(),
    take: z.coerce.number().int().min(1).max(100).optional(),
  }),
});

export const sendMessageSchema = z.object({
  params: publicIdParam,
  body: z.object({
    body: z.string().min(1).max(MAX_MESSAGE_LENGTH),
    // Makes a retried optimistic send resolve to the original message rather
    // than a duplicate. Generated by the client, unique per conversation.
    client_nonce: z.string().min(8).max(64).optional(),
    attachment: z
      .object({
        url: z.string().url().max(1000),
        name: z.string().max(200),
        size: z.number().int().positive().max(20 * 1024 * 1024),
      })
      .optional(),
  }),
});

export const markReadSchema = z.object({
  params: publicIdParam,
  body: z.object({
    last_message_id: z.number().int().positive().optional(),
  }),
});

export const muteSchema = z.object({
  params: publicIdParam,
  body: z.object({ is_muted: z.boolean() }),
});

export const createSupportSchema = z.object({
  body: z.object({
    subject: z.string().min(2).max(120),
    body: z.string().min(1).max(MAX_MESSAGE_LENGTH),
  }),
});

// ------------------------------------------------------------------ admin ---

export const adminListSchema = z.object({
  query: z.object({
    type: z.enum(["BOOKING", "SUPPORT"]).optional(),
    status: z.enum(["OPEN", "PENDING", "CLOSED"]).optional(),
    q: z.string().max(120).optional(),
    flagged: z
      .enum(["0", "1"])
      .optional()
      .transform((v) => v === "1"),
    unassigned: z
      .enum(["0", "1"])
      .optional()
      .transform((v) => v === "1"),
    page: z.coerce.number().int().min(1).optional(),
    pageSize: z.coerce.number().int().min(1).max(100).optional(),
  }),
});

export const adminIdParamSchema = z.object({
  params: z.object({ id: z.coerce.number().int().positive() }),
});

export const adminSendSchema = z.object({
  params: z.object({ id: z.coerce.number().int().positive() }),
  body: z.object({
    body: z.string().min(1).max(MAX_MESSAGE_LENGTH),
    // An internal note stays in the panel: it never reaches the participants
    // and never touches their unread badge.
    internal: z.boolean().optional(),
  }),
});

export const adminUpdateSchema = z.object({
  params: z.object({ id: z.coerce.number().int().positive() }),
  body: z.object({
    status: z.enum(["OPEN", "PENDING", "CLOSED"]).optional(),
    assign_to_me: z.boolean().optional(),
  }),
});

export const adminMessageParamSchema = z.object({
  params: z.object({ messageId: z.coerce.number().int().positive() }),
});
